language: csharp
dist: trusty
mono:
  - 4.0.5
solution: Recurly.sln
install:
  - nuget restore Recurly.sln
  - nuget install xunit.runners -Version 2.0.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Recurly.sln
  - mono ./testrunner/xunit.runners.2.0.0/tools/xunit.console.clr4.exe ./Test/bin/Release/Recurly.Test.dll
